port: 8001
database:
  host: localhost
  port: 5432
  db: ordersdb
  user: postgres
  max-open-conn: 30
  max-idle-conn: 15
  conn-max-lifetime: 5m
redis:
  address: "localhost:6379"
  call-timeout: 10s
  idle-timeout: 10m
  max-active: 50
  max-conn-lifetime: 0
  max-idle: 10
  key-expiration: 3600
